---
- name: Create Config from netbox Data
  gather_facts: no
  hosts: all
  connection: local
  become: false
  vars:
    server: "https://192.168.0.251"
    endpoint1: "/api/dcim/devices/?limit=1000"
    endpoint2: "/api/dcim/interfaces/?limit=30000"
    endpoint3: "/api/ipam/ip-addresses/?limit=5000"
    endpoint4: "/api/ipam/vrfs/?limit=5000"
    netbox_token: "7435d9eb9841dc8a941417a0993fc531c3dc35ca"
  tasks:
    # Make a Netbox API call to retrieve devices'components
    - name: Get Device List from Netbox
      uri:
        url: "{{ server }}{{ endpoint1 }}"
        headers:
          Authorization: "Token {{ netbox_token }}"
          Accept: 'application/json'
        body_format: json
        method: GET
        status_code: [200, 201]
        timeout: 30
        validate_certs: false
        return_content: no
      register: netbox_devices
      run_once: yes

    - name: Get Interfaces List from Netbox
      uri:
        url: "{{ server }}{{ endpoint2 }}"
        headers:
          Authorization: "Token {{ netbox_token }}"
          Accept: 'application/json'
        body_format: json
        method: GET
        status_code: [200, 201]
        timeout: 30
        validate_certs: false
        return_content: no
      register: netbox_ifaces
      run_once: yes

    - name: Get IPAM datas from Netbox
      uri:
        url: "{{ server }}{{ endpoint3 }}"
        headers:
          Authorization: "Token {{ netbox_token }}"
          Accept: 'application/json'
        body_format: json
        method: GET
        status_code: [200, 201]
        timeout: 30
        validate_certs: false
        return_content: no
      register: netbox_ipaddr
      run_once: yes

    - name: Get VRF List from Netbox
      uri:
        url: "{{ server }}{{ endpoint4 }}"
        headers:
          Authorization: "Token {{ netbox_token }}"
          Accept: 'application/json'
        body_format: json
        method: GET
        status_code: [200, 201]
        timeout: 30
        validate_certs: false
        return_content: no
      register: netbox_vrfs
      run_once: yes

    - local_action:
        module: copy
        content: "{{ netbox_devices | to_nice_yaml }}"
        dest: /Users/jeremierouzet/jeysible/netbox_dynamic_inventory/inventory_output/netbox_devices_create_v2.yml

    - local_action:
        module: copy
        content: "{{ netbox_devices | to_nice_json }}"
        dest: /Users/jeremierouzet/jeysible/netbox_dynamic_inventory/inventory_output/netbox_devices_create_v2.json

    - local_action:
        module: copy
        content: "{{ netbox_ifaces | to_nice_yaml }}"
        dest: /Users/jeremierouzet/jeysible/netbox_dynamic_inventory/inventory_output/netbox_ifaces_create_v2.yml

    - local_action:
        module: copy
        content: "{{ netbox_ifaces | to_nice_json }}"
        dest: /Users/jeremierouzet/jeysible/netbox_dynamic_inventory/inventory_output/netbox_ifaces_create_v2.json

    - local_action:
        module: copy
        content: "{{ netbox_ipaddr | to_nice_yaml }}"
        dest: /Users/jeremierouzet/jeysible/netbox_dynamic_inventory/inventory_output/netbox_ipaddr_create_v2.yml

    - local_action:
        module: copy
        content: "{{ netbox_ipaddr | to_nice_json }}"
        dest: /Users/jeremierouzet/jeysible/netbox_dynamic_inventory/inventory_output/netbox_ipaddr_create_v2.json

    - local_action:
        module: copy
        content: "{{ netbox_vrfs | to_nice_yaml }}"
        dest: /Users/jeremierouzet/jeysible/netbox_dynamic_inventory/inventory_output/netbox_vrfs_create_v2.yml

    - local_action:
        module: copy
        content: "{{ netbox_vrfs | to_nice_json }}"
        dest: /Users/jeremierouzet/jeysible/netbox_dynamic_inventory/inventory_output/netbox_vrfs_create_v2.json

    - name: setDeviceName
      ansible.builtin.debug:
        msg: "{{ netbox_devices.json.results | to_json | from_json | community.general.json_query(jmesquery) }}"
      vars:
        jmesquery: "[?name==`jeyniper01`].name"
        #jmesquery: "device_name[?contains(name,'jeyniper05')].name"
        #Should be >> jmesquery: "[?contains(name,'jeyniper05')].name"
      register: device_name

    - name: Generate Junos Config from Jinja2
      ansible.builtin.file:
        path: /Users/jeremierouzet/jeysible/config
        state: directory

    - name: Generate Junos Config from Jinja2 & Netbox
      template:
        src: "/Users/jeremierouzet/jeysible/templates/juniper/router/router_juniper_full_cfg.j2"
        dest: "/Users/jeremierouzet/jeysible/config/{{ device_name.msg[0] }}.cfg"
      delegate_to: localhost
