---
- name: Assign IPs
  gather_facts: no
  hosts: all
  vars_prompt:
    - name: netbox_role
      prompt: What is the Netbox role planned for the device(s) ?
      private: false
  connection: local
  become: false
  vars:
    server: "https://192.168.0.251"
    endpoint1: "/api/dcim/devices/?limit=1000"
    netbox_token: "7435d9eb9841dc8a941417a0993fc531c3dc35ca"
  tasks:
    # Make a Netbox API call to retrieve devices'components
    - name: Get Device List from Netbox
      uri:
        url: "{{ server }}{{ endpoint1 }}"
        headers:
          Authorization: "Token {{ netbox_token }}"
          Accept: 'application/json'
        body_format: json
        method: GET
        status_code: [200, 201]
        timeout: 30
        validate_certs: false
        return_content: no
      register: netbox_devices
      run_once: yes

    - name: QueryDeviceName
      ansible.builtin.debug:
        msg: "{{ netbox_devices.json.results | to_json | from_json | community.general.json_query(jmesquery) }}"
      vars:
        jmesquery: "[?device_type.manufacturer.display=='Cisco Systems' && role.display=='ToBeDefined'].{Name: name, IP: custom_fields.dev_lpbk }"
      register: device_name

    - name: Debug for learning purpose
      debug:
        msg: "Device's name is {{ device_name.msg[item].Name }}, and ZTP IP is {{ device_name.msg[item].IP }}"
      loop: "{{ device_name.msg }}"
      loop_control:
        index_var: item

    - name: Print device role planned for the devices
      ansible.builtin.debug:
        msg: The Nebox role for that device is {{ netbox_role }}

    - name: NetBox API connection check
      ansible.builtin.uri:
        url: "{{ server }}"
        headers:
          Authorization: "Token {{ netbox_token }}"
          Accept: 'application/json'
        body_format: json
        method: GET
        status_code: [200, 201]
        timeout: 30
        validate_certs: false
      register: netbox_api_check

    - name: Show result NetBox API check
      debug:
        var: netbox_api_check

    - name: Upload Data to NETBOX
      netbox.netbox.netbox_device:
        netbox_url: "{{ server }}"
        netbox_token: "{{ netbox_token }}"
        data:
          name: "{{ device_name.msg[item].Name }}"
          device_role: "{{ netbox_role }}"
        state: present
        validate_certs: false
      loop: "{{ device_name.msg }}"
      loop_control:
        index_var: item
      when: netbox_api_check.status == 200
