---
- name: Configure Restconf
  hosts: router_cisco
  gather_facts: no
  tasks:
  - name: Config Restconf
    cisco.ios.ios_config:
      lines:
      - restconf
    vars:
      ansible_connection: network_cli
      ansible_network_os: ios
      ansible_user: "{{ device_username }}"
      ansible_password: "{{ device_password }}"
