---
- name: Create Report from netbox Data
  gather_facts: no
  hosts: all
  connection: local
  become: false
  vars:
    server: "https://192.168.0.251"
    endpoint: "/api/dcim/devices/"
  tasks:
    # Make a Netbox API call to retrieve devices'components
    - name: Get Device List from Netbox
      ansible.builtin.uri:
        url: "{{ server }}{{ endpoint }}"
        headers:
          Authorization : Token 7435d9eb9841dc8a941417a0993fc531c3dc35ca
          Accept: 'application/json'
        body_format: json
        method: GET
        status_code: [200, 201]
        timeout: 30
        validate_certs: no
        return_content: no
      register: netbox_datas

    #- name: debug
    #  ansible.builtin.debug:
    #    var: netbox_datas

    # Allow to Display informations registered previously
    - name: Check Netbox Datas
      debug:
        var: netbox_datas

    # Allow to Display messages including informations registered previously
    - name: Check Netbox Datas
      debug:
        msg: "Router name is {{ netbox_datas.json.results[item].name }}, it runs Network OS {{ netbox_datas.json.results[item].platform.name }}"
      loop: "{{ netbox_datas.json.results }}"
      loop_control:
        index_var: item

    # Allow to make a local copy of the informations registered previously into Nice Json
    - local_action:
        module: copy
        content: "{{ netbox_datas | to_nice_json }}"
        dest: /Users/jeremierouzet/jeysible/netbox_dynamic_inventory/inventory_output/netbox_report_v2.json

    # Allow to make a local copy of the informations registered previously into Nice Yaml
    - local_action:
        module: copy
        content: "{{ netbox_datas | to_nice_yaml }}"
        dest: /Users/jeremierouzet/jeysible/netbox_dynamic_inventory/inventory_output/netbox_report_v2.yml

    # Allow to Display the Hostname of the devices thanks to the informations registered previously with loop to iterate through multiples devices thanks to the list index value
    - name: Run for all Nodes
      debug:
        var: netbox_datas.json.results[item].name
      loop: "{{ netbox_datas.json.results }}"
      loop_control:
        index_var: item

    # Allow to Generate a Report thanks to the informations registered previously with For loop to iterate through multiples devices
    - name: Generate Report
      ansible.builtin.blockinfile:
        block:  |
            netbox_datas.json:
            {% for device_name in netbox_datas.json.results %}
              - { node: {{ device_name.name }}, runs Network OS: {{ device_name.platform.name }}, and has Ipv4: {{ device_name.primary_ip.address }}}
            {% endfor %}
        path: /Users/jeremierouzet/jeysible/netbox_dynamic_inventory/inventory_report/netbox_report_v2.yaml
        create: yes
