---
# First play - Recover DCIM/Devices datas from Infrahub thanks to Rest Api Call
- name: Config Junos context BGP
  gather_facts: no
  hosts: all
  connection: local
  become: false
  vars:
    server: "https://192.168.0.251"
    endpoint1: "/api/dcim/devices/?limit=1000"
    infrahub_token: "7435d9eb9841dc8a941417a0993fc531c3dc35ca"
  tasks:
##### Make a Infrahub API call to retrieve devices'components related to dcim/devices
    - name: Get Device List from Infrahub
      uri:
        url: "{{ server }}{{ endpoint1 }}"
        headers:
          Authorization: "Token {{ infrahub_token }}"
          Accept: 'application/json'
        body_format: json
        method: GET
        status_code: [200, 201]
        timeout: 30
        validate_certs: false
        return_content: no
      register: infrahub_devices
      run_once: yes

##### Parse recovered datas from Infrahub DCIM Apps with jmesquery
    - name: QueryDeviceName
      ansible.builtin.debug:
        msg: "{{ infrahub_devices.json.results | to_json | from_json | community.general.json_query(jmesquery) }}"
      vars:
        jmesquery: "[?device_type.display=='SRX300' && name=='jeyniper01'].{Name: name, loopback: custom_fields.dev_lpbk, rr1: custom_fields.rr1, rr2: custom_fields.rr2 }"
      register: device_name

##### Display debug result of jmesquery for learning purpose with recovered datas from Infrahub DCIM Apps.
    - name: Debug for learning purpose
      debug:
        msg: "Device's name is {{ device_name.msg[item].Name }}, loopback address is {{ device_name.msg[item].loopback }}, First Route-Reflector is  {{ device_name.msg[item].rr1 }}, Secondary Route-Reflector is {{ device_name.msg[item].rr2 }}"
      loop: "{{ device_name.msg }}"
      loop_control:
        index_var: item

##### Output Datas recovered for learning purpose into Nice YAML & JSON format
    - local_action:
        module: copy
        content: "{{ device_name | to_nice_yaml }}"
        dest: /Users/jeremierouzet/jeysible/infrahub_dynamic_inventory/inventory_output/juniper/router/config_ctxt_bgp/config_ctxt_bgp_device_name.yml

    - local_action:
        module: copy
        content: "{{ device_name | to_nice_json }}"
        dest: /Users/jeremierouzet/jeysible/infrahub_dynamic_inventory/inventory_output/juniper/router/config_ctxt_bgp/config_ctxt_bgp_device_name.json

##### Generate Junos Config Directory
    - name: Generate Junos Config Directory
      ansible.builtin.file:
        path: /Users/jeremierouzet/jeysible/config
        state: directory

##### Render Junos Config thanks to Jinja2 Template
    - name: Generate Junos Config from Jinja2 & Infrahub
      template:
        src: "/Users/jeremierouzet/jeysible/templates/juniper/router/v2/router_juniper_ctxt_bgp_v2.j2"
        dest: "/Users/jeremierouzet/jeysible/config/juniper/{{ device_name.msg[item].Name }}.cfg"
      loop: "{{ device_name.msg }}"
      loop_control:
        index_var: item
      delegate_to: localhost
