$ANSIBLE_VAULT;1.1;AES256
31336263363164383639303839616636666166663533363337393564656230363339623734376339
3763633136626635643065366165653434323735663061300a356432316565666136633034313839
36636531373230376338663662383965316561313639343562366238346365323266323933666339
3062663231316531630a663263343937303635373662366438646430323864333261316265663834
66653333623238623939333137373933636563386535363837393835646363326636353262383937
65373836396230383163623635333033653864323733646262656261336637313938346234346338
33356466393863633933613430396366386431393265363634336639656461313738336335376330
38306334333731393461636565353238653830656538333339383461383036636434663264383265
39313362626265653231383361323632346464666135623930623230636264643239323431363730
3736323537313562333263316161643065613761623065323764
