---
tasks:
  # query a list of devices
  - name: Obtain list of devices from NetBox
    debug:
      msg: >
        "Device {{ item.value.display_name }} (ID: {{ item.key }}) was manufactured by {{ item.value.device_type.manufacturer.name }}"
     loop: "{{ query('netbox.netbox.nb_lookup', 'devices', api_endpoint='http://localhost/', api_filter='role=management tag=Dell'), token='<redacted>') }}"
