---
- name: Initial Playbook
  hosts: Router_Cisco:Router_Juniper
  gather_facts: no
  tasks:
  - name: Display Hostname
    debug:
      msg: "Router name is {{ hostname }}"
  - name: Display OS
    debug:
      msg: "{{ hostname }} is running {{ os }}"
