---
  gather_facts: no
  hosts: infrahub
  connection: local
  become: false
  vars:
    server: "http://192.168.0.237:8000"
    endpoint1: "/api/dcim/devices/?limit=1000"
    infrahub_token: "7435d9eb9841dc8a941417a0993fc531c3dc35ca"
  tasks:
    # Make a Infrahub API call to retrieve devices'components
    - name: Get Device List from Infrahub
      uri:
        url: "{{ server }}{{ endpoint1 }}"
        headers:
          Authorization: "Token {{ infrahub_token }}"
          Accept: 'application/json'
        body_format: json
        method: GET
        status_code: [200, 201]
        timeout: 30
        validate_certs: false
        return_content: no
      register: infrahub_devices
      run_once: yes


    - name: QueryDeviceCiscoSyslogServer
      ansible.builtin.debug:
        msg: "{{ infrahub_devices.json.results | to_json | from_json | community.general.json_query(jmesquery) }}"
      vars:
        jmesquery: "[?device_type.manufacturer.display=='Cisco Systems'].{Name: name, snmp_srv2: custom_fields.snmp_server2}"
      register: ciscodevices

    - name: Debug for learning purpose
      debug:
        msg: "Device's name is {{ ciscodevices.msg[item].Name }},  snmp server 2 is {{ ciscodevices.msg[item].snmp_srv2 }}"
      loop: "{{ ciscodevices.msg }}"
      loop_control:
        index_var: item

    - name: Generate Cisco Config Directory
      ansible.builtin.file:
        path: /Users/jeremierouzet/jeysible/config
        state: directory

    - name: Generate Cisco Config from Jinja2 & Infrahub - Cisco_Devices
      template:
        src: "/Users/jeremierouzet/jeysible/templates/cisco/common/v2/common_cisco_ctxt_syslog_v2.j2"
        dest: "/Users/jeremierouzet/jeysible/config/cisco/{{ ciscodevices.msg[item].Name }}.cfg"
      loop: "{{ ciscodevices.msg }}"
      loop_control:
        index_var: item
      delegate_to: localhost

    - name: Generate Cisco Facts from previous generated config file
      set_fact:
        command_to_push: "{{ lookup('file', '/Users/jeremierouzet/jeysible/config/cisco/{{ ciscodevices.msg[item].Name }}.cfg') }}"
      with_items:
         - "{{ ciscodevices.msg }}"
      loop: "{{ ciscodevices.msg }}"
      loop_control:
        index_var: item

    - name: debug
      ansible.builtin.debug:
        var: command_to_push

    - local_action:
        module: copy
        content: "{{ ciscodevices | to_nice_yaml }}"
        dest: /Users/jeremierouzet/jeysible/infrahub_dynamic_inventory/inventory_output/cisco/common/config_ctxt_syslog/config_ctxt_syslog_device_name.yml

    - local_action:
        module: copy
        content: "{{ ciscodevices | to_nice_json }}"
        dest: /Users/jeremierouzet/jeysible/infrahub_dynamic_inventory/inventory_output/cisco/common/config_ctxt_syslog/config_ctxt_syslog_device_name.json
