---
- name: Config Cisco context Syslog
  gather_facts: no
  hosts: infrahub
  connection: local
  become: false
  vars:
    server: "http://192.168.0.237:8000"
    endpoint1: "/api/dcim/devices/?limit=1000"
    infrahub_token: "7435d9eb9841dc8a941417a0993fc531c3dc35ca"
  tasks:
    # Make a Infrahub API call to retrieve devices'components
    - name: Get Device List from Infrahub
      uri:
        url: "{{ server }}{{ endpoint1 }}"
        headers:
          Authorization: "Token {{ infrahub_token }}"
          Accept: 'application/json'
        body_format: json
        method: GET
        status_code: [200, 201]
        timeout: 30
        validate_certs: false
        return_content: no
      register: infrahub_devices
      run_once: yes

    - name: QueryDeviceName
      ansible.builtin.debug:
        msg: "{{ infrahub_devices.json.results | to_json | from_json | community.general.json_query(jmesquery) }}"
      vars:
        jmesquery: "[?device_role.display=='Switch_Cisco'].{Name: name, snmp_srv2: custom_fields.snmp_server2}"
      register: Switch_Cisco

    - name: Debug for learning purpose
      debug:
        msg: "Device's name is {{ Switch_Cisco.msg[item].Name }},  snmp server 2 is {{ Switch_Cisco.msg[item].snmp_srv2 }}"
      loop: "{{ Switch_Cisco.msg }}"
      loop_control:
        index_var: item

    - name: QueryDeviceName
      ansible.builtin.debug:
        msg: "{{ infrahub_devices.json.results | to_json | from_json | community.general.json_query(jmesquery) }}"
      vars:
        jmesquery: "[?device_role.display=='Router_CE_Cisco'].{Name: name, snmp_srv2: custom_fields.snmp_server2}"
      register: Router_CE_Cisco

    - name: Debug for learning purpose
      debug:
        msg: "Device's name is {{ Router_CE_Cisco.msg[item].Name }},  snmp server 2 is {{ Router_CE_Cisco.msg[item].snmp_srv2 }}"
      loop: "{{ Router_CE_Cisco.msg }}"
      loop_control:
        index_var: item

    - name: QueryDeviceName
      ansible.builtin.debug:
        msg: "{{ infrahub_devices.json.results | to_json | from_json | community.general.json_query(jmesquery) }}"
      vars:
        jmesquery: "[?device_role.display=='Router_PE_Cisco'].{Name: name, snmp_srv2: custom_fields.snmp_server2}"
      register: Router_PE_Cisco

    - name: Debug for learning purpose
      debug:
        msg: "Device's name is {{ Router_PE_Cisco.msg[item].Name }},  snmp server 2 is {{ Router_PE_Cisco.msg[item].snmp_srv2 }}"
      loop: "{{ Router_PE_Cisco.msg }}"
      loop_control:
        index_var: item

    - name: Generate Cisco Config Directory
      ansible.builtin.file:
        path: /Users/jeremierouzet/jeysible/config
        state: directory

    - name: Generate Cisco Config from Jinja2 & Infrahub
      template:
        src: "/Users/jeremierouzet/jeysible/templates/cisco/common/v2/common_cisco_ctxt_syslog_v2.j2"
        dest: "/Users/jeremierouzet/jeysible/config/cisco/{{ Switch_Cisco.msg[item].Name }}.cfg"
      loop: "{{ Switch_Cisco.msg }}"
      loop_control:
        index_var: item
      delegate_to: localhost

    - name: Generate Cisco Facts from previous generated config file
      set_fact:
        command_to_push: "{{ lookup('file', '/Users/jeremierouzet/jeysible/config/cisco/{{ Switch_Cisco.msg[item].Name }}.cfg') }}"
      with_items:
         - "{{ Switch_Cisco.msg }}"
      loop: "{{ Switch_Cisco.msg }}"
      loop_control:
        index_var: item

    - name: Generate Cisco Config from Jinja2 & Infrahub
      template:
        src: "/Users/jeremierouzet/jeysible/templates/cisco/common/v2/common_cisco_ctxt_syslog_v2.j2"
        dest: "/Users/jeremierouzet/jeysible/config/cisco/{{ Router_CE_Cisco.msg[item].Name }}.cfg"
      loop: "{{ Router_CE_Cisco.msg }}"
      loop_control:
        index_var: item
      delegate_to: localhost

    - name: Generate Facts from previous generated config file
      set_fact:
        command_to_push: "{{ lookup('file', '/Users/jeremierouzet/jeysible/config/cisco/{{ Router_CE_Cisco.msg[item].Name }}.cfg') }}"
      with_items:
         - "{{ Router_CE_Cisco.msg }}"
      loop: "{{ Router_CE_Cisco.msg }}"
      loop_control:
        index_var: item

    - name: Generate Cisco Config from Jinja2 & Infrahub
      template:
        src: "/Users/jeremierouzet/jeysible/templates/cisco/common/v2/common_cisco_ctxt_syslog_v2.j2"
        dest: "/Users/jeremierouzet/jeysible/config/cisco/{{ Router_PE_Cisco.msg[item].Name }}.cfg"
      loop: "{{ Router_PE_Cisco.msg }}"
      loop_control:
        index_var: item
      delegate_to: localhost

    - name: Generate Facts from previous generated config file
      set_fact:
        command_to_push: "{{ lookup('file', '/Users/jeremierouzet/jeysible/config/cisco/{{ Router_PE_Cisco.msg[item].Name }}.cfg') }}"
      with_items:
         - "{{ Router_PE_Cisco.msg }}"
      loop: "{{ Router_PE_Cisco.msg }}"
      loop_control:
        index_var: item

    - name: debug
      ansible.builtin.debug:
        var: command_to_push

    - name: Push command to devices
      cisco.ios.ios_config:
        src: "/Users/jeremierouzet/jeysible/templates/cisco/common/v2/common_cisco_ctxt_syslog_v2.j2"
        backup: yes
        backup_options:
          filename: "{{ device_name.msg[item].Name }}.cfg"
          dir_path: /Users/jeremierouzet/jeysible/config/cisco/backup
        save_when: "modified"
      with_items:
         - "{{ device_name.msg }}"
      loop_control:
        index_var: item
      vars:
        ansible_connection: network_cli
        ansible_network_os: ios
        ansible_user: "{{ device_username }}"
        ansible_password: "{{ device_password }}"
        ansible_host: "{{ device_name.msg[item].Name }}"

    - local_action:
        module: copy
        content: "{{ device_name | to_nice_yaml }}"
        dest: /Users/jeremierouzet/jeysible/infrahub_dynamic_inventory/inventory_output/cisco/common/config_ctxt_snmp/config_ctxt_snmp_device_name.yml

    - local_action:
        module: copy
        content: "{{ device_name | to_nice_json }}"
        dest: /Users/jeremierouzet/jeysible/infrahub_dynamic_inventory/inventory_output/cisco/common/config_ctxt_snmp/config_ctxt_snmp_device_name.json
